apiVersion: v1
kind: Pod

metadata:
  name: pod2
  labels:
    env: prod
    type: beckend

spec:
  containers:
    - name: containername
      image: coolgourav147/nginx-custom
      env:
        - name: myname
          value: Gagan
        - name: City
          value: Luncknow
