apiVersion: v1

kind: ReplicationController

metadata:
  name: firstrcset
  labels:
    appname: voatingapp

spec:
  replicas: 5
  template: 
    metadata:
      name: nginxpod
      labels:
        type: app

    spec:
      containers:
        - name: containername
          image: coolgourav147/nginx-custom
