apiVersion: v1

kind: Service

metadata:
  name: myservice1
  labels:
    servicelbl: nginxservice

spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 9000
      targetPort: 80
  selector:
    type: app
