apiVersion: v1
kind: Service

metadata:
  name: deployservice
  labels:
    name: prodservice
    
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 9000
      targetPort: 80
  selector:
    app: myapp
