---

- name: build and push
  hosts: ansible
  become: true

  tasks:
  - name: remove current docker image
    command: docker rmi webtest-image
    ignore_errors: yes

  - name: building docker image
    command: docker build -t webtest-image .
    args:
      chdir: /opt/kubernetes

  - name: tagging image
    command: docker tag webtest-image gagansingh92/webtest-image:v1.2

  - name: push image to dockerhub
    command: docker push gagansingh92/webtest-image:v1.2

- name: deploy on docker host
  hosts: kmaster
  become: true
  user: root

  tasks:
  - name: apply deployment on kmaster node
    command: kubectl apply -f /tmp/simple-devops-project/deploy.yml 

  - name: apply service on kmaster
    command: kubectl apply -f /tmp/simple-devops-project/svc-deploy.yml

