version: '3.1'

services:
  drupal:
    image: drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres
    envoinoment:
        - POSTGRES_DB=drupal
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=pass


volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
