apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    name: webservice
    env: prod
spec:
  type: LoadBalancer
  ports:
    - nodePort: 32000     #outside cluster
      port: 8080          #pod level
      targetPort: 8080    #cluser level
  selector:
    type: frontend
